# .pre-commit-config.yaml

repos:
- repo: https://github.com/psf/black
  rev: 24.10.0
  hooks:
    - id: black
      language_version: python3
      args: ['--line-length', '79']

- repo: https://github.com/PyCQA/flake8
  rev: 7.1.1
  hooks:
    - id: flake8
      args: ['--max-line-length=79']
